---

- name: Install NeoVim requirements
  apt: name=silversearcher-ag

- name: Install NeoBundle
  sudo_user: "{{username}}"
  git: repo=https://github.com/Shougo/neobundle.vim dest="/home/{{username}}/.nvim/bundle/neobundle.vim"

- name: Add neovim dependency from pip system libraries
  pip: name=neovim

- name: Creating fonts folders
  file: path={{item}} state=directory owner="{{username}}" group="{{username}}"
  with_items:
    - "/home/{{username}}/.fonts/"
    - "/home/{{username}}/.config/fontconfig/conf.d/"

- name: Downloading fonts
  sudo_user: "{{username}}"
  get_url: url={{item.url}} dest={{item.dest}}
  with_items:
      - { url: "https://github.com/powerline/powerline/raw/develop/font/PowerlineSymbols.otf", dest: "/home/{{username}}/.fonts/" }
      - { url: "https://github.com/powerline/powerline/raw/develop/font/10-powerline-symbols.conf", dest: "/home/{{username}}/.config/fontconfig/conf.d/" }
  register: fonts_downloaded

- name: Install fontconfig
  apt: name=fontconfig

- name: Updating font cache
  sudo_user: "{{username}}"
  shell: fc-cache -vf "/home/{{username}}/.fonts/"
  when: fonts_downloaded.changed