---


# - name: Mysql | Set passwords
#   debconf: name='mysql-server-5.6' question='mysql-server/{{ item }}' vtype='password' value=''
#   with_items:
#     - root_password
#     - root_password_again


- name: Install mysql-server-5.6
  apt: pkg=mysql-server-5.6 state=installed
  tags: mysql

- include: workbench.yml
