---

- name: Java | Add repository
  apt_repository: repo='ppa:webupd8team/java' state=present

- name: Java | Autoaccept license for Java
  debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

- name: Java | Install Java 8
  apt: name=oracle-java8-installer state=present


