---


# - name: Mysql | Set passwords
#   debconf: name='mysql-server-5.6' question='mysql-server/{{ item }}' vtype='password' value=''
#   with_items:
#     - root_password
#     - root_password_again


- include: mysql.yml
- include: mongodb2.yml
- include: workbench.yml
